{{- if and .Values.networkPolicy.enabled (not .Values.networkPolicy.enabled_l7_waf) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "i2b2-frontend.fullname" . }}-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "i2b2-frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "i2b2-frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  {{- if .Values.networkPolicy.ingress }}
  {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  # Default Deny Ingress: Empty ingress list means deny all unless explicitly allowed
  [] 
  {{- end }}
  egress:
  {{- if .Values.networkPolicy.egress }}
  {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
    # Always allow DNS resolution to kube-system
    - to:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kube-system
      ports:
      - protocol: UDP
        port: 53 # Allow DNS resolution to kube-system
      - protocol: TCP
        port: 53 # Allow DNS resolution to kube-system
{{- end }}
