# Prometheus Probes configuration
prober:
#  url: chorus-prometheus-blackbox-exporter.prometheus.svc
#  port: 9115
#  scheme: http
#  path: /probe

# List of environments to create probes for
environments:
# Example:
#   - name: dev
#     targets:
#       - alertmanager.dev.chorus-tre.ch
#       - auth.dev.chorus-tre.ch
#       - grafana.dev.chorus-tre.ch
#       - harbor.dev.chorus-tre.ch
#       - prometheus.dev.chorus-tre.ch
