apiVersion: v2
description: An open source trusted cloud native registry that stores, signs, and scans content.
name: harbor
version: 0.0.7
dependencies:
  - name: harbor
    version: 1.17.1
    repository: https://helm.goharbor.io

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
  - name: floriansipp
    email: florian.sipp@chuv.ch
