apiVersion: v2
description: |
  A Helm chart that collects custom resource definitions (CRDs) from cert-manager,
  allowing for seamless integration with GitOps tools
name: cert-manager-crds
version: 1.18.2
maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
  - name: johaab
    email: jonathan.haab@chuv.ch
