---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.chorusBackend.acceptanceTestsNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chorus-backend-acceptance-test
  namespace: {{ .Values.chorusBackend.acceptanceTestsNamespace }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "serviceaccounts"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "create", "update", "patch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificates", "certificaterequests"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chorus-backend-acceptance-test
  namespace: {{ .Values.chorusBackend.acceptanceTestsNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default {{ .Values.serviceAccount.name | default chorus-ci-sa }} }}
    namespace: {{ .Release.Namespace | default argo}}
roleRef:
  kind: Role
  name: chorus-backend-acceptance-test
  apiGroup: rbac.authorization.k8s.io
