apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chorus-ci-rolebinding
  namespace: {{ .Release.Namespace | default "argo" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chorus-ci-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default "chorus-ci-sa" }}
