apiVersion: v1
kind: Secret
metadata:
  name: chorus-ci-sa.service-account-token
  namespace: {{ .Release.Namespace | default argo }}
  annotations:
    kubernetes.io/service-account.name: chorus-ci-sa
type: kubernetes.io/service-account-token
