{{- range .Values.priorityClasses }}
{{- if .enabled }}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .name }}
  labels:
    {{- include "chorusPriorityClass.labels" $ | nindent 4 }}
value: {{ .value }}
globalDefault: {{ .globalDefault | default false }}
{{- if .preemptionPolicy }}
preemptionPolicy: {{ .preemptionPolicy }}
{{- end }}
description: {{ .description | quote }}
{{- end }}
{{- end }}
