apiVersion: v2
description: Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
name: keycloak
version: 0.0.38
dependencies:
  - name: keycloak
    version: 24.5.2
    repository: https://charts.bitnami.com/bitnami

maintainers:
  - name: floriansipp
    email: florian.sipp@chuv.ch
  - name: iDmple
    email: nathalie.casati@chuv.ch
