apiVersion: v2
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
name: ingress-nginx
version: 0.0.8
dependencies:
  - name: ingress-nginx
    version: 4.13.3
    repository: https://kubernetes.github.io/ingress-nginx

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
