apiVersion: v2
name: juicefs-csi-driver
description: A Helm chart for JuiceFS CSI Driver.
version: 0.0.13
dependencies:
  - name: juicefs-csi-driver
    version: 0.31.1
    repository: https://juicedata.github.io/charts/

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
  - name: floriansipp
    email: florian.sipp@chuv.ch
