apiVersion: v2
name: juicefs-s3-gateway
description: A Helm chart for JuiceFS S3 Gateway.
version: 0.0.4
dependencies:
  - name: juicefs-s3-gateway
    version: 0.11.3
    repository: https://juicedata.github.io/charts/

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
