apiVersion: v2
description: Helm chart for Grafana Loki and Grafana Enterprise Logs supporting monolithic, simple scalable, and microservices modes.
name: loki
version: 0.0.1
dependencies:
  - name: loki
    version: 6.51.0
    repository: https://grafana.github.io/helm-charts

maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch
  - name: floriansipp
    email: florian.sipp@chuv.ch
  - name: johaab
    email: jonathan.haab@chuv.ch
