apiVersion: v2
description: Matomo, formerly known as Piwik, is a real time web analytics program. It provides detailed reports on website visitors.
name: matomo
maintainers:
  - name: iDmple
    email: nathalie.casati@chuv.ch

version: 0.0.11
dependencies:
  - name: matomo
    version: 11.0.0
    repository: https://charts.bitnami.com/bitnami
